

services:
  redis:
    image: redis:7.2
    ports:
      - "6379:6379"
    networks:
      - app_net # Mantenemos red explícita

  web:
    build:
      context: .
      dockerfile: Dockerfile # NO necesita cambios
    command: daphne -b 0.0.0.0 -p 8000 webappdl.asgi:application
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - redis
      - selenium-chrome # Depende del nuevo servicio Selenium
    environment:
      - PYTHONUNBUFFERED=1
      # --- CAMBIO: Apunta al nuevo servicio y endpoint estándar ---
      - SELENOID_URL=http://selenium-chrome:4444/wd/hub
      # ----------------------------------------------------------
    restart: unless-stopped
    networks:
      - app_net
  # --- NUEVO SERVICIO CELERY WORKER ---
  celery-worker:
    build:
      context: .         # Usa el mismo Dockerfile que 'web'
      dockerfile: Dockerfile
    command: celery -A webappdl worker -l INFO  # Comando para iniciar el worker
    volumes:
      - .:/app             # Comparte el código fuente igual que 'web'
    environment:
      - PYTHONUNBUFFERED=1
      - SELENOID_URL=http://selenium-chrome:4444/wd/hub # Necesita acceso a settings
      # Añade otras variables de entorno que 'web' necesite si acceden a settings
    depends_on:
      - web                # Asegura que 'web' (Django) esté listo
      - redis              # Necesita el broker
      - selenium-chrome    # Necesitará interactuar con Selenium
    restart: unless-stopped
    networks:
      - app_net
  # --- FIN NUEVO SERVICIO CELERY WORKER ---
  # --- NUEVO SERVICIO: Selenium Standalone con Chrome y VNC ---
  selenium-chrome:
    # Usamos la imagen oficial de Selenium con Chrome y VNC (debug)
    image: selenium/standalone-chrome:4.18.1-20240224
    container_name: selenium-chrome
    ports:
      - "4444:4444" # Puerto Selenium WebDriver
      - "7900:7900" # Puerto VNC (Contraseña default: secret)
    # shm_size sigue siendo importante para Chrome
    shm_size: '2gb'
    networks:
      - app_net
    restart: unless-stopped
  # --- FIN NUEVO SERVICIO ---

  # --- SERVICIOS 'selenoid' y 'selenoid-ui' ELIMINADOS ---

# --- Definición de la Red (Mantenemos la explícita) ---
networks:
  app_net:
    driver: bridge
# -----------------------------------------------------
