# Generated by Django 4.2.20 on 2025-04-19 22:57

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('url', models.URLField(help_text='URL del sitio a validar', max_length=2000)),
                ('reference_json_content', models.TextField(help_text='Contenido del JSON de referencia')),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('active', 'Activa'), ('error', 'Error'), ('completed', 'Completada')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
