# Generated by Django 4.2.20 on 2025-04-28 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='session',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='session',
            name='reference_json_content',
        ),
        migrations.AddField(
            model_name='session',
            name='captured_data',
            field=models.JSONField(blank=True, help_text='DataLayers capturados durante la sesión interactiva', null=True),
        ),
        migrations.AddField(
            model_name='session',
            name='reference_schema',
            field=models.JSONField(blank=True, help_text='Schema JSON de referencia para la validación (generado desde el input)', null=True),
        ),
        migrations.AddField(
            model_name='session',
            name='report_file',
            field=models.FileField(blank=True, help_text='Archivo del reporte de validación generado', null=True, upload_to='validation_reports/'),
        ),
        migrations.AddField(
            model_name='session',
            name='selenium_session_id',
            field=models.CharField(blank=True, help_text='ID de la sesión específica en Selenium Grid/Standalone', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='session',
            name='validation_results',
            field=models.JSONField(blank=True, help_text='Resultados detallados de la validación vs el schema', null=True),
        ),
        migrations.AddField(
            model_name='session',
            name='vnc_url',
            field=models.URLField(blank=True, help_text='URL para acceder a la sesión VNC del navegador remoto', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='session',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendiente'), ('starting', 'Iniciando'), ('waiting_user', 'Esperando Usuario'), ('finish_requested', 'Finalización Solicitada'), ('processing', 'Procesando'), ('completed', 'Completada'), ('error', 'Error')], default='pending', max_length=20),
        ),
    ]
